name: Tests

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "v*"
        
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
      - uses: pnpm/action-setup@v2
        with:
          version: 7.30.3
      - run: pnpm commit-check